### ISSUE TITLE
조건부 렌더링 -> 로그인을 해야만 다른 페이지에 접근 가능한

### ISSUE THREAD

**Issue by JongeunKeum** [WhatHappenedTo2nd/ft_transcendence#117]
평가받을 때, 처음 디비에 아무것도 없는 상태에서 일단 로그인 안 하면 다른 페이지 접근 못하는 걸 보여줌
그리고 로그인한 다음에 다음 진행

토큰을 가지고 접근 제한을 함

**Comment by stopminbeom** [comment]
#124 으로 해결하였습니다
